pbugnion/gmaps

docs/source/api.rst
docs/source/gmaps.rst
gmaps/maps.py
js/src/jupyter-gmaps.js

This PR allows injection of a Google Maps API key. This increases the number of requests that a user can make, and may even be necessary for some services. This addresses issue #61 .
The interface is:
```python
import gmaps
gmaps.configure(api_key="your-api-key")
m = gmaps.Map()
d = gmaps.Directions(data=[[45.0, 5.0], [46.0, 7.0], [47.0, 6.0]])
m.add_layer(d)
m
```
To unset the API key, use:
```python
gmaps.configure(api_key=None)
```
The configuration can be applied at any time, but any existing widgets will have to be reloaded (by re-executing the cell in which they are rendered) for the configuration changes to affect that widget.

Allow injecting API keys

---

js/package.json
js/src/jupyter-gmaps.js
js/webpack.config.js

This PR migrates the JavaScript to [ECMAScript 2015](https://babeljs.io/docs/learn-es2015/ and tidies the layout of the JS code. I have tried to stick to the [Airbnb style / best practice] guide(https://github.com/airbnb/javascript).
There should be no changes in browser compatibility, since the JS code is transpiled and bundled using Webpack anyway.

Improve JS code layout

---

.travis.yml
README.rst
requirements.txt

This will make me marginally more confident that we are not releasing garbage.
Test coverage remains very low, because it's not obvious how to test Jupyter widgets (this does not seem to be a solved problem). At the moment, the tests concentrate on the Python side, mostly around verifying that user input is correctly validated.

Add Travis CI

---

gmaps/maps.py
js/src/jupyter-gmaps.js

Prior to this PR, the bounds of a heatmap for which the data spanned the -180 degrees / +180 degrees line were calculated incorrectly. The bounds were calculated as:
- the most eastern latitude in the data is `min(latitudes)`
- the most western latitude is `max(latitudes)`
This doesn't work if the most eastern latitude is, e.g., 150 and the most western is -30. The map would then go from -30 all the way round to 150. This was evident in the earthquakes dataset:
Now, the bounds are calculated by assuming the data is distributed with a  [wrapped normal distribution](https://en.wikipedia.org/wiki/Wrapped_normal_distribution). We then take the latitude bounds as 2 * distribution's standard deviation (or 360 degrees, whichever is smaller). This results in much better bounds:

Calculate bounds of data layer in heatmap correctly

---

gmaps/marker.py
gmaps/tests/test_marker.py
js/src/jupyter-gmaps.js

Example:
```python
m = gmaps.Map()
locations = [
(-34.0, -59.166672),
(-32.23333, -64.433327),
]
names = ["Atucha", "Embalse"]
infos_html=["<h1>Atucha</h1>","<h2>Embalse</h2>"]
symbol_layer = gmaps.symbol_layer(locations, hover_text=names,info_html=infos_html)
m = gmaps.Map()
m.add_layer(symbol_layer)
m
```

Feature: Add InfoBox Feature to Marker

---

gmaps/marker.py
gmaps/tests/test_marker.py
js/src/jupyter-gmaps.js

Info-boxes show up even when their content is empty. This is a regression since the user has no way to specify that they don't want an info box.
This PR solves this by adding a `display_info_box` option to both the widgets and the factory functions. This can be set explicitly, or left as `None`, in which case it will default to `True` if the user has set a content for info boxes or `False` otherwise.

Infobox empty fix

---

.travis.yml

The Travis builds broke because some of the dependencies were not installing correctly. By default, Travis runs a fairly old version of pip (6.0.7 vs the current 9.0.1). pip6.0.7 doesn't seem to be able to find wheels for many of the packages, which makes the installation more complex. Forcing an update of pip before building fixes the problem.

Force pip upgrade in Travis

---

setup.py

The API  documentation wasn't building on readthedocs because it requires autodoc, which requires the module to be installed, or at least present in the path. Luckily, readthedocs lets us install the package in a virtualenv. Installing gmaps on readthedocs presented an additional complication: it failed to install because the setup script requires NPM. Actually building the documentation only requires the python parts of gmaps, though, so we just avoid building the JS part on readthedocs.

Fix read the docs

---

MANIFEST.in

This means the license file is included in source distributions and we can use it for conda-forge.

Add license file to MANIFEST.

---

js/package.json
js/src/Map.js
js/src/vendor/html2canvas.js

Prior to this PR, we used a pre-release of html2canvas (0.5.0-*). This lead to issues (e.g. issue #129) which we can fix by regressing to `0.4.1`.
Unfortunately, 0.4.1 does not work with the directions layer (see [this](https://stackoverflow.com/questions/37457945/html2canvas-screenshot-of-a-div-element-containing-google-drive-directions-map)). All the other layers work OK.

Regress to html2canvas 0.4.1

---

docs/source/export.rst

The documentation on embedding gmaps in HTML documents was both wrong and not particularly helpful. Now somewhat improved.
This addresses issue #140 in particular.

Fix documentation on embedding

---

gmaps/errors_box.py
gmaps/figure.py
js/src/Directions.js
js/src/ErrorsBox.js
js/src/Figure.js
js/src/GeoJson.js
js/src/Heatmap.js
js/src/Map.js
js/src/Marker.js
js/src/index.js
js/src/jupyter-gmaps.less
js/src/services/downloadElement.js

Prior to this PR, downloading figures as PNG was quite unreliable (issue #129 as well as general rendering issues).
This is improved by reverting to a stable version of html2canvas (PR #138). This works great, except when downloading maps containing directions (see e.g. [this](https://stackoverflow.com/questions/37457945/html2canvas-screenshot-of-a-div-element-containing-google-drive-directions-map) question on SO). This is probably acceptable (for now), but we need to give the user decent feedback. This PR introduces an error box in which to display errors like these.

Better handling of errors when downloading maps as PNGs

---

gmaps/bounds.py
gmaps/tests/test_bounds.py

Google maps doesn't allow specifying latitude bounds above 85.0 or below -85.0.

Cap latitude bounds to values allowed by Google maps

---

js/src/Directions.js
js/src/ErrorsBox.js
js/src/Figure.js
js/src/GMapsLayer.js
js/src/GeoJson.js
js/src/Heatmap.js
js/src/Map.js
js/src/Marker.js
js/src/Toolbar.js

It's 2017. ES6 classes offer a much nicer syntax than Backbone's `extend`.
This PR should have no effect on the functionality. It just makes the JS code easier to read and write.

Use ES6 classes

---

gmaps/directions.py
gmaps/tests/test_directions.py
js/src/Directions.js

Added avoid_ferries, avoid_highways, avoid_tolls and optimize_waypoints to the python api.

4 new options for the directions layer (Issue: 151)

---

gmaps/bounds.py
gmaps/tests/test_bounds.py

Broke up the functionality in location_bounds to a case for N > 1 and a case for N ==1.  N > 1 is the original code (subtracting the case for N == 1).  For the N == 1 case, both the lower and upper bounds would be the same as the location (longitude) passed.

Added case for a single location

---

docs/source/api.rst
gmaps/__init__.py
gmaps/bicycling.py
gmaps/figure.py
gmaps/transit.py
js/src/Bicycling.js
js/src/Transit.js
js/src/index.js

This PR lets users add a [transit layer](https://developers.google.com/maps/documentation/javascript/trafficlayer) to the base map.
This is what's left to do:

Transit layer

---

README.rst
docs/source/export.rst
gmaps/_version.py
gmaps/bicycling.py
gmaps/directions.py
gmaps/errors_box.py
gmaps/figure.py
gmaps/geojson_layer.py
gmaps/heatmap.py
gmaps/maps.py
gmaps/marker.py
gmaps/toolbar.py
gmaps/transit.py
js/package.json
js/src/ErrorsBox.js
js/src/Figure.js
js/src/GMapsLayer.js
js/src/GeoJson.js
js/src/Map.js
js/src/Marker.js
js/src/Toolbar.js
js/src/extension.js
js/webpack.config.js
requirements.txt
setup.py
tasks.py

This starts the migration to jupyter-widgets 7.0.0 and geojson 2.0.0. This PR is now available as version `0.6.0-alpha2`.
```
pip install gmaps==0.6.0-alpha2
jupyter nbextension enable --py --sys-prefix gmaps
```

Migrate to ipywidgets 7

---

js/src/Bicycling.js
js/src/Transit.js

Prior to this commit, the bicycling and transit layers could not be exported to PNG because they were not explicitly marked as exportable. Since html2canvas seems to work reasonably with these, there is no good reason not to mark them as exportable.

Allow exporting bicycling and transit layers to PNG

---

js/src/ErrorsBox.js
js/src/Figure.js
js/src/GMapsLayer.js
js/src/Map.js
js/src/Toolbar.js
js/src/defaults.js

This helps with exports when the defaults are not included.

Include the version number in JavaScript

---

gmaps/tests/test_heatmap.py
test-requirements.txt

A merge to master broke the build because of an upgrade in Flake8. This fixes the flake8 problem and hardcodes the version dependency for flake8 so we avoid future regressions.

Flake8 fixes

---

gmaps/marker.py
gmaps/tests/test_marker.py
js/src/Marker.js

As part of building up the marker layer, we had disabled clicking on markers. This meant info boxes didn't work any more. Now fixed.

Fix marker clickable state

---

gmaps/geotraitlets.py
gmaps/heatmap.py
gmaps/tests/test_heatmap.py
js/src/Heatmap.js

Prior to this PR, weighted heatmaps combined weight and location data into a single traitlet. This doesn't make much sense -- having two separate traitlets allows changing locations and weights independently, which will help resolve issue #188 .
Left to do:

Split locations and weights into separate traitlets for weighted heatmaps

---

js/src/Drawing.js

This was explicitly disabled, mostly because it was untested. Now fixed.
Addresses issue #224 .

Allow downloading drawing layer as PNG

---

docs/source/tutorial.rst

The tutorial used a mix of double and single quotes in the examples. We now consistenly use single quotes.

Consistently use single quotes in tutorial

---

js/src/Map.js

PR #240 introduced a log in `loadConfiguration`. We logged the configuration passed to `gmaps`, including the API key, which is probably a bad thing.

Avoid unnecessary log

---

js/src/ErrorsBox.js
js/src/Map.js
js/src/Toolbar.js
js/src/jupyter-gmaps.less

Because of changes in the notebook CSS, the styling around the errors box had disappeared. This PR re-enables it.

Add styling to errors box

---

gmaps/directions.py
gmaps/drawing.py
gmaps/geojson_layer.py
gmaps/geotraitlets.py
gmaps/marker.py
gmaps/tests/test_drawing.py
gmaps/tests/test_geotraitlets.py
gmaps/tests/test_marker.py

Prior to this PR, we were redefining opacities everywhere as a `Float(min=0.0, max=1.0)` traitlet. This centralises the definition into a single `Opacity` traitlet.
This PR should make no functional changes.

Define Opacity traitlet

---

gmaps/heatmap.py
gmaps/tests/test_heatmap.py

The `data` traitlet was deprecated from the `Heatmap` and `WeightedHeatmap` widgets in PR #211. They were replaced by split out:
- locations traitlet for the `Heatmap` widget
- locations and weights traitlets for the `WeightedHeatmap` widget.
This PR removes the data traitlet completely.

Remove deprecated data traitlet from heatmap

---

gmaps/figure.py
gmaps/geotraitlets.py
gmaps/maps.py
gmaps/tests/test_figure.py
js/src/Map.js

[tilt](https://developers.google.com/maps/documentation/javascript/reference/3.exp/map#MapOptions.tilt) is an option provided by the Google Maps JavaScript API, but prior to this has not been exposed by this library.
Please excuse the unpolished code - I expect it will take some editing to get this feature ready for merging, but I figured the earlier I could get feedback on my overall approach, the better.
In particular I don't really know what I'm doing with traitlets, and perhaps tilt should default to None rather than 45 and the JavaScript setTilt call should only happen if tilt is specified.
Furthermore, since tilt doesn't apply to all maps types, gmaps could intelligently validate that setting tilt makes sense for the map type requested (although Google Maps itself accepts setTilt …

Add tilt option to gmaps.figure

---

dev-install

We used to run `npm run build` as part of the installation process.
Not only is this redundant (we build the JavaScript as part of the
next `pip install -e .`), it was also broken since the `build` script
was renamed `build:all`.
Addresses issue #255 .

Remove broken step in dev-install

---

js/package.json
js/src/Drawing.js
js/src/ErrorsBox.js
js/src/Marker.js
js/src/Toolbar.js
js/src/embed.js
js/src/jupyter-gmaps-embed.less
js/src/jupyter-gmaps.less
js/src/labplugin.js
js/webpack.config.js

The dependency on Twitter Bootstrap makes reasoning about styles unnecessarily complicated and introduces unexpected side-effects, like issue #265.
We should port the styles we need and get rid of the dependency.
---
Left to do:

Remove bootstrap dependency

---

tasks.py

This PR:
- updates the release tasks to work against the new semver API
- uses twine to upload, rather than `python setup.py upload`.

Update release tasks

---

js/src/Marker.js

Prior to this PR, there was a mismatch between symbol defaults in the Python side and the client. This meant that using the default values of `fill_opacity`, `scale` and `stroke_opacity` Python-side lead to unexpected behaviour when embedding (even if the default values were explicitly specified).
Reported in issue #275 .

Correctly propagate defaults for symbols to the client

---

docs/source/app_tutorial.rst

The last paragraph of the 'building applications' tutorial did not render. Now fixed.

Formatting fix in docs

---

gmaps/marker.py
gmaps/tests/test_marker.py

Prior to this PR, marker layers and symbol layers had to have at least one marker / symbol. This doesn't play well with dynamic applications, where it's reasonable to sometimes have no markers or symbols. See e.g. [the example application](https://jupyter-gmaps.readthedocs.io/en/latest/app_tutorial.html#updating-symbols-in-response-to-other-widgets) where the app should still work if both checkboxes are de-selected.
This PR also updates the tests to test against the marker and symbol layers directly.

Support empty marker and symbol layer

---

js/package.json
js/src/Map.js

This PR updates the version of the Google Maps JavaScript API to 3.34. 
Google Maps Loader 3.3.0 currently defaults to 3.31, so we hard-code the version number.

Update Google Maps JS API version to 3.34

---

gmaps/errors_box.py
gmaps/figure.py
gmaps/maps.py
gmaps/tests/test_directions.py
gmaps/tests/test_errors_box.py
gmaps/tests/test_figure.py
gmaps/tests/test_maps.py

Prior to this PR, running the tests raised some warnings. This fixes them, and introduces additional unit tests for the changes.

Fix deprecation warnings on traitlets

---

README.rst
gmaps/_version.py
js/package.json

This fixes the dependencies on the Jupyter widget registry.
Left to do:

Update for JupyterLab 1.0.
